### PR TITLE
[RPA-504.2] Fix scaling of RPA section.

### PR DESCRIPTION
**Pull request by star-in-the-jar**

### CODE REVIEW

**Comment by star-in-the-jar** [comment]
resolutions:
image
image
image
image
image
image

**Review by star-in-the-jar — COMMENTED** [review]
Self reviewed.

**Review by star-in-the-jar — COMMENTED** [review]
Self reviewed

**Review by star-in-the-jar — COMMENTED** [review]
Self reviewed

**Review by FranekMarciniak — APPROVED** [review]

**Pull request merged**
