### PR TITLE
[RPA-913] Add worksheet field to Excel action Set cell

### PR DESCRIPTION
**Pull request by star-in-the-jar**
## Description
analogously to https://github.com/runbotics/runbotics/pull/311

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

I agree to the terms of the RunBotics Contributor License Agreement.

### CODE REVIEW

**Review by star-in-the-jar — COMMENTED** [review]
Self reviewed

**Review by marcin-depcik — COMMENTED** [review]
Changes reviewed, it looks fine to me.

**Review by star-in-the-jar — COMMENTED** [review]
self reviewed

**Review by Klau-Sam — APPROVED** [review]

**Review by star-in-the-jar — COMMENTED** [review]
self reviewed

**Pull request merged**
